site_name: Easy.DB Docs

theme:
  name: material

nav:
    - Getting Started: 'index.md'
    - Setup: 'setup.md'
    - Classes: 'classes.md'
    - About: 'about.md'
    - License: 'license.md'